# Generated by Django 5.2.11 on 2026-02-26 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('priority', models.CharField(choices=[('low', '🟢 Past'), ('medium', "🟡 O'rta"), ('high', '🔴 Yuqori'), ('urgent', '🚨 Shoshilinch')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', '⏳ Kutmoqda'), ('in_progress', '🔄 Jarayonda'), ('completed', '✅ Bajarildi'), ('cancelled', '❌ Bekor qilindi')], default='pending', max_length=15)),
                ('category', models.CharField(choices=[('work', '💼 Ish'), ('personal', '👤 Shaxsiy'), ('study', "📚 O'qish"), ('health', "💪 Sog'liq"), ('finance', '💰 Moliya'), ('other', '📌 Boshqa')], default='personal', max_length=15)),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Muddat sanasi')),
                ('due_time', models.TimeField(blank=True, null=True, verbose_name='Muddat vaqti')),
                ('estimated_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Taxminiy vaqt (daqiqa)')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='goals.goal', verbose_name="Bog'liq maqsad")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vazifa',
                'verbose_name_plural': 'Vazifalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
