# Generated by Django 5.2.11 on 2026-02-26 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice_type', models.CharField(choices=[('general', '💬 Umumiy maslahat'), ('task_plan', '📋 Vazifa rejasi'), ('time_management', '⏰ Vaqt boshqaruvi'), ('goal_advice', "🎯 Maqsad bo'yicha maslahat"), ('productivity', '🚀 Samaradorlik')], default='general', max_length=20)),
                ('user_message', models.TextField()),
                ('ai_response', models.TextField()),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Suhbat',
                'verbose_name_plural': 'AI Suhbatlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
