# Generated by Django 5.2.11 on 2026-03-29 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_habits', '0002_habit_duration_minutes'),
        ('ai_habits', '0003_habit_target_days'),
    ]

    operations = [
    ]
