# Generated by Django 5.2.11 on 2026-02-26 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Maqsad nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('category', models.CharField(choices=[('career', '💼 Karyera'), ('education', "📚 Ta'lim"), ('health', "💪 Sog'liq"), ('finance', '💰 Moliya'), ('personal', '🌟 Shaxsiy rivojlanish'), ('relationship', '❤️ Munosabatlar'), ('hobby', '🎨 Hobby'), ('other', '📌 Boshqa')], default='personal', max_length=20)),
                ('status', models.CharField(choices=[('pending', '⏳ Boshlanmagan'), ('in_progress', '🔄 Jarayonda'), ('completed', '✅ Bajarildi'), ('paused', "⏸️ To'xtatildi"), ('cancelled', '❌ Bekor qilindi')], default='pending', max_length=15)),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='Progress (%)')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Muddat')),
                ('why', models.TextField(blank=True, verbose_name='Nima uchun (motivatsiya)')),
                ('reward', models.CharField(blank=True, max_length=200, verbose_name='Mukofot')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maqsad',
                'verbose_name_plural': 'Maqsadlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
